---
  #этот плейбук делает пинг по вебу
- name: ping
  hosts: web
  #become: yes
  gather_facts: yes
  tasks:
  - name: Distribution
    debug: msg="{{ ansible_distribution }}"
  - name: Distribution version
    debug: msg="{{ ansible_distribution_version}}"
  - name: Distribution major version
    debug: msg="{{ ansible_distribution_major_version }}"

  - name: Create service service
    template:
      src: report.txt
      dest: '/mydir/report.txt'
      mode: 0644

  - name: consul_user_shell
    shell: "mount |grep /dev/vd |awk '{print $5}'"
    register: file_system

  - name: Output disk information
    debug:
      var:  file_system.stdout
