---
- name: ping
  hosts: web
  #become: yes
  gather_facts: yes
  tasks:
  - name: Populate service facts
    service_facts:

  - name: Print service facts only stopped
    debug:
      var: ansible_facts.services [item]
      verbosity: 2
    when: ansible_facts.services [item].state== 'stopped'
    loop: "{{ ansible_facts.services | list }}"
