---
- name: Install
  apt:
    name:
        - python3-pip
        - virtualenv
        - gunicorn

- name: Update pip
  shell:  'pip3 install pip -U'

- name: pip
  pip:
    name:
      - aiohttp
      - aiohttp_jinja2
      - jinja2
      - gunicorn
    virtualenv: /opt/app/venv
    virtualenv_python: python3
