---
- name: ping
  hosts: web
  #become: yes
  gather_facts: yes
  tasks:
  - name: Install package with multiple repos disabled
    yum:
      enablerepo: "epel"

  - name: Install apach
    yum:
      name: httpd
      state: latest

  - name: reboot
    reboot:

  - name: disabled service httpd and ensure it is not masked
    ansible.builtin.systemd:
      name: httpd
      enabled: no

  - name: Reboot a slow machine that might have lots of updates to apply
    reboot:
      pre_reboot_delay : 10

  - name: Populate service facts
    service_facts:

  - name: Print service facts
    ansible.builtin.debug:
      var: ansible_facts.services['httpd.service']
      verbosity: 2

  - name: Enable service httpd
    ansible.builtin.systemd:
      name: httpd
      enabled: yes
      daemon_reload: yes

  - name: Stop service cron on debian, if running
    ansible.builtin.systemd:
      name: httpd
      state: stopped

  - name: Restart service cron on centos, in all cases, also issue daemon-reload to pick up config changes
    ansible.builtin.systemd:
      state: started
      name: httpd

  - name: reboot
    reboot:

  - name: Find all
    find:
      paths:
        - /etc/httpd/conf
        - /etc/httpd/conf.d
